### ISSUE TITLE
How should ICRA 2019 demo be launched?

### ISSUE THREAD

**Issue by NicksonYap** [bitcraze/crazyflie-firmware-experimental#2]
Hi @krichardsson & @ataffanel,

I have tested 2 different CFs with the non-experimental repo and they both localize nicely when controlled with Xbox 360 controller, and in the `lighthouse_openvr_grab.py` example

I'm currently trying the ICRA 2019 demo using 1 CF set at 0/80/2M

Changing the start/stop/takeoff params from from Parameters Tab in CFClient causes no effect.
And when using the Xbox 360 controller to fly in Position Hold mode, the CF will just flip

I do notice that the demo is meant for 8 CFs and there is a `control_tower.py` and `towergui.py`
But what's the proper way to launch the demo?

Thanks!

**Comment by NicksonYap** [comment]
It seems there are more info here:

https://www.bitcraze.io/events/icra2019/
https://www.youtube.com/watch?v=xkT943nTTUA
https://www.youtube.com/watch?v=OmnDqUjj42M

I'll try to modify `control_tower.py` to work on 1 CF first

**Comment by krichardsson** [comment]
The demo should work with any number of CF from 1 to 8, it uses the ones that are available. Actually booth the control tower and the CFs can be restarted at any time and should pick up and continue as before. There is no need to modify the tower for 1 CF. Provided you have set the correct frequency/address + Lighthouse geometry in the CF it should work out of the box. 

There is functionality in the code to reposition the CF on the charging pad when landing if it is not charging (and thus missed the pad). If you don't have wireless chargers you will have to modify this since the CF will continuously will try to reposition.

**Comment by NicksonYap** [comment]
Thanks, I got both CFs flying

And just like you said CF will keep trying to reposition as I don't have a charging pad 
(going to make one, it's very cool!)

However, why does the CF flip when trying to control in Position Hold mode using Xbox 360 controller? 

I'm hoping to fix it so that we can test the set up before flying using LH Deck

**Comment by krichardsson** [comment]
I have created an issue for the position hold problem in bitcraze/crazyflie-firmware#462
